config/routes.rb
Rails.application.routes.draw do

  root 'groups#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :groups do
    resources :topics do
    post 'add_post' => 'topics#create_post'
  end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :topics
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  belongs_to :group 
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :groups
  has_many :topics

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :user_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    #@topics = Topic.all
    redirect_to group_path(:id => params[:group_id])
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @post = Post.new
    @posts = Post.order(:id).page params[:page]
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  def create_post
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.topic_id = params[:topic_id]
  #  @post.group_id = params[:group_id]

      if @post.save
        redirect_to group_topic_path(id: params[:topic_id])
      end

  end



  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.group_id = params[:group_id]

    respond_to do |format|
      if @topic.save
        format.html { redirect_to group_topic_path(:id => @topic.id), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to group_topic_path(:id => @topic.id), notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to group_path(:id => params[:group_id]), notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description, :group_id, :user_id)
    end

    def post_params
      params.require(:post).permit(:content)
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  has_many :groups
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:" %>
      </h2>
      <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>
<%= render 'form' %>
<%= link_to 'Show', @group %>
\|
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<table class="table table-hover">
  <thead>
    <tr class="row">
      <th class="col-md-2">Name</th>
      <th class="col-md-5">Description</th>
      <th class="col-md-2">Owner</th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
      <th class="col-md-1"></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr class="row">
        <td>
          <%= group.name %>
        </td>
        <td>
          <%= group.description %>
        </td>
        <td>
          <%= group.user_id %>
        </td>
        <td>
          <%= link_to 'Show', group %>
        </td>
        <td>
          <%= link_to 'Edit', edit_group_path(group) %>
        </td>
        <td>
          <%= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>
<%= render 'form' %>
<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Topics</h1>

<table class= "table table-hover">
  <thead>
    <tr class>
      <th>Name</th>
      <th>Description</th>
      <th>Group</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @group.topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= topic.group_id %></td>
        <td><%= topic.user_id %></td>
        <td><%= link_to 'Show', group_topic_path(:group_id => topic.group.id, :id => topic.id) %></td>
        <td><%= link_to 'Edit', edit_group_topic_path(:group_id => topic.group.id, :id => topic.id) %></td>
        <td><%= link_to 'Destroy', group_topic_path(:group_id => topic.group.id, :id => topic.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_group_topic_path(:group_id => @group.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peach on Rails Forum</title>
  <link href='https://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<!-- insert that to navbar -->



  <%= render 'shared/nav' %>

<!-- insert that to navbar END-->


  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
 <div class="container-fluid">
   <div class="navbar-header">
     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
     </button>
     <a class="navbar-brand" href="/">Peach on Rails Forum</a>
   </div>
   <div class="collapse navbar-collapse" id="myNavbar">
     <ul class="nav navbar-nav">
       <li class="active"><a href="/">Home</a></li>
       <li></li>
       <li></li>
       <li></li>
     </ul>

     <% if user_signed_in? %>
     <ul class="nav navbar-nav navbar-right">
       Logged in as <strong><%= current_user.email %></strong>.
       <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
       <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
     </ul>

     <% else %>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
         <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
         <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
       </ul>
     <% end %>
   </div>
 </div>
</nav>
<!--
<h1></h1>

</p> -->

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>



  <div class="form">
    <%= form_for @post, :url => group_topic_add_post_path(topic_id: @topic.id) do |f| %>
      <div class="field">
        <%= f.label :post, "Napisz post"%><br>
        <%= f.text_area :content %>

      </div>
      <div class="actions">
        <%= f.submit "Dodaj", class: "btn-submit"%>
      </div>
      <% end %>
  </div>


<table class= "table table-hover">
  <thead>
    <tr>
      <th>Content</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>

        <td><%= post.content %></td>
        <td><%= post.created_at.strftime('%c') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @posts %>

<br>

<%= link_to 'Back', group_path(:id => params[:group_id]) %>